name: Build

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: yarn install
    - name: Build
      run: PATH="/usr/lib/llvm-10/bin:$PATH" yarn build
    - run: yarn pack
    - run: |
        mkdir gh-upload
        cd gh-upload
        mv ../shibunyan-*.tgz ./
        cp ../package.json ./
        cp ../dist/shibunyan.umd.min.js ./
    - uses: actions/upload-artifact@v2
      with:
        name: package
        path: gh-upload/*